/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnimationSelector: typeof import('./src/components/AnimationSelector.vue')['default']
    CinematicAnimations: typeof import('./src/components/CinematicAnimations.vue')['default']
    CinematicIntro: typeof import('./src/components/CinematicIntro.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ViewControls: typeof import('./src/components/ViewControls.vue')['default']
  }
}
