/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnimationSelector: typeof import('./src/components/animation/AnimationSelector.vue')['default']
    CameraControls: typeof import('./src/components/animation/CameraControls.vue')['default']
    CinematicAnimations: typeof import('./src/components/animation/CinematicAnimations.vue')['default']
    ControlsHint: typeof import('./src/components/ui/ControlsHint.vue')['default']
    LoadingIndicator: typeof import('./src/components/ui/LoadingIndicator.vue')['default']
    PanoramaSwitcher: typeof import('./src/components/animation/panorama-switcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
  }
}
